# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 * * * ?"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./dist/contribution-snake/github-contribution-grid-snake.gif
            ./contribution-snake/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main


          message: ':rocket: Update'
